## Data Preprocessing Tools

### Importing the libraries

Some of the basic libraries used in ML are
- Numpy - Allow to work with arrays
- Pandas - Allow to import dataset, play with data
- Matplotlib - Allow to plot charts

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing the Dataset

In any dataset, we have features and dependent variable vector

- Features - column with which we are going to predict dependent variabl vector
- Dependent variables(or label) - column we want to predict

**iloc** - stands for locate indexes - take indexes for rows and columns we want to extract from dataset

Most dataset we use to train model have features in first n-1 columns while last column contains the label

In [2]:
dataset = pd.read_csv('./data.csv')
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [3]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [4]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

### Taking care of missing data

We have missing salaries in our data. We can use SimpleImputer than can be used to fill mean or median data in cells where data is not present

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[['Age', 'Salary']])
X[['Age', 'Salary']] = imputer.transform(X[['Age', 'Salary']])

In [6]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

### Encoding categorical data

To avoid misrepresented co-relation between categorical variables, we can use one-hot encoding.

#### Encoding the Independent variable

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['Country'])], remainder='passthrough')

X = ct.fit_transform(X)

In [8]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

#### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Splitting the dataset into training and test set

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [12]:
X_train

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [13]:
X_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

### Feature Scaling

- This is scaling so that all variables take value in a range
- This is done after splitting so that test set is treated as a new set (like real world)
- Also, feature scaling on original dataset before splitting, we can grab some data from test set like mean, median etc. So as to provide information leakage we should do scaling after splitting

Standardisation:
works for every use case

$$ x_{stand} = \frac{x - x_{mean}}{\sigma(x)} $$

Normalisation:
recommended when we have normal values for our features

$$ x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}} $$

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train[:, 3:] = scaler.fit_transform(X_train[:, 3:])
X_test[:, 3:] = scaler.transform(X_test[:, 3:])

In [15]:
X_train

array([[ 0.        ,  0.        ,  1.        , -0.19159184, -1.07812594],
       [ 0.        ,  1.        ,  0.        , -0.01411729, -0.07013168],
       [ 1.        ,  0.        ,  0.        ,  0.56670851,  0.63356243],
       [ 0.        ,  0.        ,  1.        , -0.30453019, -0.30786617],
       [ 0.        ,  0.        ,  1.        , -1.90180114, -1.42046362],
       [ 1.        ,  0.        ,  0.        ,  1.14753431,  1.23265336],
       [ 0.        ,  1.        ,  0.        ,  1.43794721,  1.57499104],
       [ 1.        ,  0.        ,  0.        , -0.74014954, -0.56461943]])

In [16]:
X_test

array([[ 0.        ,  1.        ,  0.        , -1.46618179, -0.9069571 ],
       [ 1.        ,  0.        ,  0.        , -0.44973664,  0.20564034]])